/**
 * AirQuality.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AirQualityOpenAQContractsAttributionDTO } from './airQualityOpenAQContractsAttributionDTO';


export interface AirQualityOpenAQContractsLicenceDTO { 
    id?: number;
    name?: string | null;
    attribution?: AirQualityOpenAQContractsAttributionDTO | null;
    dateFrom?: string | null;
    dateTo?: string | null;
}

