/**
 * AirQuality.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AirQualityOpenAQContractsIdNameDTO } from './airQualityOpenAQContractsIdNameDTO';
import { AirQualityOpenAQContractsLicenceDTO } from './airQualityOpenAQContractsLicenceDTO';
import { AirQualityOpenAQContractsSensorDTO } from './airQualityOpenAQContractsSensorDTO';
import { AirQualityOpenAQContractsCoordinatesDTO } from './airQualityOpenAQContractsCoordinatesDTO';
import { AirQualityOpenAQContractsDateDTO } from './airQualityOpenAQContractsDateDTO';
import { AirQualityOpenAQContractsCountryDTO } from './airQualityOpenAQContractsCountryDTO';


export interface AirQualityOpenAQContractsSensorLocationDTO { 
    id?: number;
    name?: string | null;
    locality?: string | null;
    timezone?: string | null;
    country?: AirQualityOpenAQContractsCountryDTO | null;
    owner?: AirQualityOpenAQContractsIdNameDTO | null;
    provider?: AirQualityOpenAQContractsIdNameDTO | null;
    isMobile?: boolean;
    isMonitor?: boolean;
    instruments?: Array<AirQualityOpenAQContractsIdNameDTO> | null;
    sensors?: Array<AirQualityOpenAQContractsSensorDTO> | null;
    coordinates?: AirQualityOpenAQContractsCoordinatesDTO | null;
    licenses?: Array<AirQualityOpenAQContractsLicenceDTO> | null;
    bounds?: Array<number> | null;
    distance?: number;
    datetimeFirst?: AirQualityOpenAQContractsDateDTO | null;
    datetimeLast?: AirQualityOpenAQContractsDateDTO | null;
}

