/**
 * AirQuality.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AirQualityOpenAQContractsParameterDTO } from './airQualityOpenAQContractsParameterDTO';


export interface AirQualityOpenAQContractsSensorDTO { 
    id?: number;
    name?: string;
    parameter?: AirQualityOpenAQContractsParameterDTO | null;
}

