/**
 * AirQuality.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AirQualityOpenAQContractsParameterDTO } from './airQualityOpenAQContractsParameterDTO';


export interface AirQualityOpenAQContractsCountryDTO { 
    id?: number;
    code?: string | null;
    name?: string | null;
    datetimeFirst?: string | null;
    datetimeLast?: string | null;
    parameters?: Array<AirQualityOpenAQContractsParameterDTO>;
}

