/**
 * AirQuality.Api
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateDTO } from './dateDTO';

export interface CoverageDTO {
  expectedCount?: number | null;
  expectedInterval?: string;
  observedCount?: number | null;
  observedInterval?: string;
  percentComplete?: number | null;
  percentCoverage?: number | null;
  datetimeFrom?: DateDTO;
  datetimeTo?: DateDTO;
}
