/**
 * AirQuality.Api
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DateDTO {
  id?: number;
  utc?: string | null;
  local?: string | null;
}
