/**
 * AirQuality.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinatesDTO } from './coordinatesDTO';
import { DateDTO } from './dateDTO';


export interface LatestDTO { 
    datetime?: DateDTO;
    value?: number | null;
    coordinates?: CoordinatesDTO;
}

