/**
 * AirQuality.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributionDTO } from './attributionDTO';


export interface LicenceDTO { 
    id?: number;
    name?: string | null;
    attribution?: AttributionDTO | null;
    dateFrom?: string | null;
    dateTo?: string | null;
}

