/**
 * AirQuality.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SensorLocationDTO } from './sensorLocationDTO';


export interface LocationsResponse { 
    locations?: Array<SensorLocationDTO>;
}

