/**
 * AirQuality.Api
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParameterDTO } from './parameterDTO';

export interface ParametersResponse {
  parameters?: Array<ParameterDTO>;
}
