/**
 * AirQuality.Api
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SensorDTO } from './sensorDTO';

export interface SensorsResponse {
  sensors?: Array<SensorDTO>;
}
