/**
 * AirQuality.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicenceDTO } from './licenceDTO';
import { CoordinatesDTO } from './coordinatesDTO';
import { CountryDTO } from './countryDTO';
import { SensorDTO } from './sensorDTO';
import { IdNameDTO } from './idNameDTO';
import { DateDTO } from './dateDTO';


export interface SensorLocationDTO { 
    id?: number;
    name?: string | null;
    locality?: string | null;
    timezone?: string | null;
    country?: CountryDTO | null;
    owner?: IdNameDTO | null;
    provider?: IdNameDTO | null;
    isMobile?: boolean;
    isMonitor?: boolean;
    instruments?: Array<IdNameDTO> | null;
    sensors?: Array<SensorDTO> | null;
    coordinates?: CoordinatesDTO | null;
    licenses?: Array<LicenceDTO> | null;
    bounds?: Array<number> | null;
    distance?: number;
    datetimeFirst?: DateDTO | null;
    datetimeLast?: DateDTO | null;
}

