/**
 * AirQuality.Api
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SummaryDTO {
  min?: number | null;
  q02?: any | null;
  q25?: any | null;
  median?: any | null;
  q75?: any | null;
  q98?: any | null;
  max?: number | null;
  avg?: number | null;
  sd?: any | null;
}
